### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by JeremyRand** [hlandau/nccald#1]
Any reason not to use https://github.com/emersion/go-ical and https://github.com/emersion/go-webdav ?  (Based on briefly looking at their issue trackers, they seem like a competent upstream.)

**Comment by hlandau** [comment]
The only thing needed for the CalDAV functionality is a single PUT request. The use of go-webdav was considered and rejected as there's no need to pull in this entire library and it's tightly coupled to a different iCal library.
